services:
  - name: easyvideo-bot
    type: web
    runtime: python3.10
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    autoDeploy: true
